[book]
authors = ["Niko Matsakis"]
language = "en"
src = "md"
title = "SACP: Symposium's Extensions to ACP"
description = "Documentation for Symposium's extensions to the Agent Client Protocol"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/symposium-dev/symposium-acp"
edit-url-template = "https://github.com/symposium-dev/symposium-acp/edit/main/{path}"
